import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';

import StoreInitializer from '@/app/providers/StoreInitializer';
import StoreProvider from '@/app/providers/StoreProvider';

import './globals.css';

const inter = Inter({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Frontend Engineer Challenge',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <StoreProvider>
          <StoreInitializer>
            {children}
            <Toaster
              toastOptions={{ duration: 2000 }}
              position="top-center"
              reverseOrder={false}
            />
          </StoreInitializer>
        </StoreProvider>
      </body>
    </html>
  );
}
